name: Update Recent Activity

on:
  schedule:
    - cron: "0 */6 * * *"   # roda a cada 6 horas
  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 10
